repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Or a newer version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-toml

-   repo: https://github.com/psf/black
    rev: 23.7.0 # Or a newer version
    hooks:
    -   id: black
        args: [--line-length=88]

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0 # Or a newer version
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length", "88"]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0 # Or a newer version
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear]
        args:
          - "--max-line-length=88"
          - "--ignore=E203,W503" # E203: whitespace before ':', W503: line break before binary operator (black compatibility)

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0 # Or use a specific version if needed
    hooks:
    -   id: prettier
        types_or: [css, javascript, json, markdown, yaml] # Add other file types if needed
        exclude: "poetry.lock" # Exclude poetry.lock as it can cause issues 