sdhubert:
  dummy_sdhubert_embedding_dim: 256

classifier:
  hidden_dim: 128
  num_classes: 2

autoencoder:
  encoding_dim: 64

timing_loss_weight: 0.5

onnx_export:
  opset_version: 11
  output_names: ["stress_logits", "recovered_timings"]
  model_onnx_path: "${model_output_dir}/speech_analyzer.onnx"

tensorrt_export: pass 